language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
script:
    #    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.clone("https://github.com/hildebrandmw/Mapper2.jl"); Pkg.test("Mapper2", coverage=true)'
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Mapper2")); using Coverage; Codecov.submit(process_folder())'
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; cd(Pkg.dir("Mapper2")); include(joinpath("docs", "make.jl"))'
